// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtbetBD55f5GOX6ma5JL4bfsNbHuS-fvY',
    appId: '1:357524149221:web:227af4c4b95b1f8d1c550c',
    messagingSenderId: '357524149221',
    projectId: 'dim0524',
    authDomain: 'dim0524.firebaseapp.com',
    databaseURL: 'https://dim0524-default-rtdb.firebaseio.com',
    storageBucket: 'dim0524.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA525-RBhlWazojS-9PAasT62ChaclWsI4',
    appId: '1:357524149221:android:6ff55ed15cd5a11d1c550c',
    messagingSenderId: '357524149221',
    projectId: 'dim0524',
    databaseURL: 'https://dim0524-default-rtdb.firebaseio.com',
    storageBucket: 'dim0524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXT1ek1XlTN_nc4-84Cvsy62PAmpQRNws',
    appId: '1:357524149221:ios:b897669ea36f68771c550c',
    messagingSenderId: '357524149221',
    projectId: 'dim0524',
    databaseURL: 'https://dim0524-default-rtdb.firebaseio.com',
    storageBucket: 'dim0524.firebasestorage.app',
    iosBundleId: 'com.example.f08EshopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXT1ek1XlTN_nc4-84Cvsy62PAmpQRNws',
    appId: '1:357524149221:ios:b897669ea36f68771c550c',
    messagingSenderId: '357524149221',
    projectId: 'dim0524',
    databaseURL: 'https://dim0524-default-rtdb.firebaseio.com',
    storageBucket: 'dim0524.firebasestorage.app',
    iosBundleId: 'com.example.f08EshopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtbetBD55f5GOX6ma5JL4bfsNbHuS-fvY',
    appId: '1:357524149221:web:e3733d98ea30ce041c550c',
    messagingSenderId: '357524149221',
    projectId: 'dim0524',
    authDomain: 'dim0524.firebaseapp.com',
    databaseURL: 'https://dim0524-default-rtdb.firebaseio.com',
    storageBucket: 'dim0524.firebasestorage.app',
  );

}